import { AdjustmentsIcon as IconAdjustments } from "@heroicons/react/solid";
import {
  ArrowRight as IconArrowRight,
  Backpack as IconBackpack,
  CalendarBlank as IconCalendar,
  CaretDown as IconCaretDown,
  Chats as IconMessage,
  Check as IconCheck,
  CheckCircle as IconCheckCircle,
  Database as IconDatabase,
  Function as IconFunction,
  GearSix as IconGear,
  HardDrives as IconStorage,
  Key as IconKey,
  List as IconMenu,
  LockLaminated as IconSignUp,
  LockSimple as IconSignOut,
  LockSimpleOpen as IconSignIn,
  Package as IconPackage,
  Rewind as IconRewind,
  Scroll as IconScroll,
  Timer as IconTimer,
} from "phosphor-react";
import {
  BsFillChatSquareFill as IconTwist,
  BsSlack as IconSlack,
} from "react-icons/bs";
import {
  FaArrowLeft as IconArrowLeft,
  FaBolt as IconBolt,
  FaBookOpen as IconDocs,
  FaChalkboardTeacher as IconEducator,
  FaCircle as IconCircle,
  FaCloud as IconCloud,
  FaCog as IconCog,
  FaCommentAlt as IconMessageQueue,
  FaDev as IconDev,
  FaDiscord as IconDiscord,
  FaFacebook as IconFacebook,
  FaFileAlt as IconCV,
  FaGithub as IconGitHub,
  FaGlobe as IconWebsite,
  FaInstagram as IconInstagram,
  FaLinkedin as IconLinkedIn,
  FaMedium as IconMedium,
  FaMoon as IconLight,
  FaProductHunt as IconProductHunt,
  FaProjectDiagram as IconKontenbase,
  FaShapes as IconRealTime,
  FaShieldAlt as IconAuth,
  FaSun as IconDark,
  FaTelegram as IconTelegram,
  FaTwitter as IconTwitter,
  FaUserNinja as IconDeveloper,
  FaYoutube as IconYouTube,
} from "react-icons/fa";
import {
  SiAmazonaws as IconAmazonEC2,
  SiAmazons3 as IconAmazonS3,
  SiApachekafka as IconKafka,
  SiCircle as IconColyseus,
  SiMongodb as IconMongoDB,
} from "react-icons/si";

export {
  IconAdjustments,
  IconAmazonEC2,
  IconAmazonS3,
  IconArrowLeft,
  IconArrowRight,
  IconAuth,
  IconBackpack,
  IconBolt,
  IconCalendar,
  IconCaretDown,
  IconCheck,
  IconCheckCircle,
  IconCircle,
  IconCloud,
  IconCog,
  IconColyseus,
  IconCV,
  IconDark,
  IconDatabase,
  IconDev,
  IconDeveloper,
  IconDiscord,
  IconDocs,
  IconEducator,
  IconFacebook,
  IconFunction,
  IconGear,
  IconGitHub,
  IconInstagram,
  IconKafka,
  IconKey,
  IconKontenbase,
  IconLight,
  IconLinkedIn,
  IconMedium,
  IconMenu,
  IconMessage,
  IconMessageQueue,
  IconMongoDB,
  IconPackage,
  IconProductHunt,
  IconRealTime,
  IconRewind,
  IconScroll,
  IconSignIn,
  IconSignOut,
  IconSignUp,
  IconSlack,
  IconStorage,
  IconTelegram,
  IconTimer,
  IconTwist,
  IconTwitter,
  IconWebsite,
  IconYouTube,
};
