export const configPricingFeatures = [
  { icon: "database", name: "Database" },
  { name: "Database Space" },
  { name: "Database Transfer" },
  { icon: "auth", name: "Auth" },
  { name: "Users" },
  { icon: "storage", name: "Storage" },
  { name: "Storage Space" },
  { name: "Storage Transfer" },
];

export const configPricingPlans = [
  {
    name: "Free",
    price: {
      EUR: "0",
      IDR: "0",
      MYR: "0",
      PHP: "0",
      SGD: "0",
      USD: "0",
    },
    note: "14 days trial",
    info: "For experiments and simple applications",
    button: {
      text: "Start from Free",
      to: "/signup",
    },
    benefits: [
      "Up to 250 MB database space",
      "Up to 5 GB database transfer bandwidth",
      "Up to 500 MB file storage space",
      "Up to 5 GB file storage transfer bandwidth",
      "Up to 500 registered users",
      "Community Support",
      // "1-day log retention",
    ],
    features: [null, "50 MB", "500 MB", null, 50, null, "250 MB", "500 MB"],
  },
  {
    name: "Professional",
    price: {
      EUR: "23",
      IDR: "360,000",
      MYR: "110",
      PHP: "1325",
      SGD: "34",
      USD: "25",
    },
    note: "/project/month",
    info: "For production, with basic usage",
    button: {
      text: "Start from Free",
      to: "/signup",
    },
    benefits: [
      "Up to 2 GB database space",
      "Up to 12 GB database transfer bandwidth",
      "Up to 25 GB file storage space",
      "Up to 12 GB file storage transfer bandwidth",
      "Up to 12,000 registered users",
      "Prioritized Team Support",
    ],
    features: [null, "8 GB", "50 GB", null, "50,000", null, "100 GB", "50 GB"],
  },
  {
    name: "Business",
    price: {
      EUR: "94",
      IDR: "1,500,000",
      MYR: "435",
      PHP: "5480",
      SGD: "134",
      USD: "99",
    },
    note: "/project/month",
    info: "For production with more custom usage",
    button: {
      text: "Start from Free",
      to: "/signup",
    },
    benefits: [
      "Up to 8 GB database space",
      "Up to 50 GB database transfer bandwidth",
      "Up to 100 GB file storage space",
      "Up to 50 GB file storage transfer bandwidth",
      "Up to 50,000 registered users",
      "Prioritized Team Support",
      // "30-day log retention",
    ],
    features: [null, "8 GB", "50 GB", null, "50,000", null, "100 GB", "50 GB"],
  },
  {
    name: "Enterprise",
    price: {
      EUR: "",
      IDR: "",
      MYR: "",
      PHP: "",
      SGD: "",
      USD: "",
    },
    note: "Contract",
    info: "For large-scale mission critical applications",
    button: {
      text: "Schedule Demo",
    },
    benefits: [
      "Everything from the Professional plan",
      "Self hosted or on-premise",
      "Point in time recovery",
      "Designated Support manager & SLAs",
      "Enterprise OAuth providers",
      "SSO & SAML",
      "Custom contracts & invoicing",
      "On-premise support",
      "24×7×365 premium enterprise support",
      // "SOC2",
    ],
    features: [
      null,
      "Unlimited",
      "Unlimited",
      null,
      "Unlimited",
      null,
      "Unlimited",
      "Unlimited",
    ],
  },
];
